import databaseConfig from './config/database.config';
import { DatabaseConfig } from './config/database-config.type';

/**
 * Single source of truth for the "which database driver?" decision at
 * bootstrap time.
 *
 * The application supports two persistence backends — relational (TypeORM) and
 * document (Mongoose). Every place in the startup path that needs to branch on
 * the active driver should call {@link isDocumentDatabase} (or
 * {@link resolveDatabaseType}) instead of reading `databaseConfig()` and
 * casting manually.
 *
 * Feature modules generated by the hygen templates still call
 * `databaseConfig()` directly inside `<database-block>` guards; that is
 * intentional so the generator stays self-contained. This helper targets the
 * **assembly layer** — `DatabaseModule.forRoot()`, seed runners, CLI tools, and
 * any future bootstrap-time code that needs the same answer.
 */
export function resolveDatabaseType(): Pick<
  DatabaseConfig,
  'isDocumentDatabase' | 'type'
> {
  const config = databaseConfig() as DatabaseConfig;
  return {
    isDocumentDatabase: config.isDocumentDatabase,
    type: config.type,
  };
}

/**
 * Convenience predicate for module-level branching:
 * ```ts
 * const driverModule = isDocumentDatabase()
 *   ? MongooseModule.forRootAsync(...)
 *   : TypeOrmModule.forRootAsync(...);
 * ```
 */
export function isDocumentDatabase(): boolean {
  return resolveDatabaseType().isDocumentDatabase;
}
